services:
  # db:
  #   image: postgres:latest
  #   container_name: trepi-postgres
  #   ports:
  #     - '${DB_PORT}:5432'
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   env_file:
  #     - ./trepi-server/.env
  #   restart: always
  #   networks:
  #     - trepi_network

  backend:
    build:
      context: ./trepi-server
      dockerfile: Dockerfile
    container_name: trepi-server
    ports:
      - '${BACKEND_PORT}:8000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      RUST_LOG: info
    restart: unless-stopped
    networks:
      - trepi_network

  frontend:
    build:
      context: ./trepi-app
      dockerfile: Dockerfile
    container_name: trepi-app
    ports:
      - '${FRONTEND_PORT}:3000'
    environment:
      API_BASE_URL: http://backend:8000/api/v1
    depends_on:
      - backend
    networks:
      trepi_network

volumes:
  pg_data:

networks:
  trepi_network:
    driver: bridge